# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class AuthStorage:
        namespaceId: str
        type: str
    class Bucket:
        name: str
        type: str
    class Database:
        databaseId: str
        type: str
    class GOOGLE_CLIENT_ID:
        type: str
        value: str
    class GatewayKv:
        namespaceId: str
        type: str
    class ProjectStorage:
        name: str
        type: str
    class WebApp:
        type: str
        url: str

