source "https://rubygems.org"

gem "sinatra", "~>4.2"
gem "thin"
gem "puma"
gem "rackup"

group :test do
  gem "rack-test"
  gem "rest-client"
  gem "rspec"
  gem "rspec_junit_formatter"
  gem "rspec-retry"
  gem "rubysl-securerandom"
end

group :development do
  gem "rerun"
end